# -*- coding: utf-8 -*-

import sys
import pandas as pd

def main(input_file, output_file):
    # 用户指定排序顺序的CB序列列表
    sort_order = [
        "TCCTACCAGT", "GCGTTGGAGC", "GATCTTACGC", "CTGATGGTCA", "CCGAGAATCC", "GCCGCAACGA", "TGAGTCTGGC", "TGCGGACCTA", "ACGGAGGCGG", "TAGATCTACT", "AATTAAGACT", "TTATTCATTC", "TTGACTTCAG", "AGAGCTATAA", "CTAAGAGAAG", "ACTCAATAGG", "CTTGCGCCGC", "GGTACTGCCT", "TAGAATTAAC", "GCCATTCTCC", "TGCCGGCAGA", "TTACCGAGGC", "ATCATATTAG", "TGGTCAGCCA", "ACTATGCAAT", "CGACGCGACT", "GATACGGAAC", "TTATCCGGAT", "TAGAGTAATA", "GCAGGTCCGT", "TCGGCCTTAC", "AGAACGTCTC", "CCAGTTCCAA", "ACTTAACCTT", "CAACCGCTAA", "GACCTTGATA", "TCTGATACCA", "GAAGATCGAG", "AAGAAGCTAG", "TCCGGCCTCG", "AGAGAAGGTT", "CATACTCCGA", "GCTAACTTGC", "GGCTGAGCTC", "CCGATTCCTG", "ACCGCCAACC", "ATAAGGAGCA", "CGAACGCCGG", "GGTATGCTTG", "AACCTGCGTA", "GGCAGACGCC", "TAGCCGTCAT", "CTAGTAGTCT", "ACGCGAGATT", "GGTATCCGCC", "AACTAGGCGC", "TCGCTAAGCA", "TATATACTAA", "ACTTGCTAGA", "AACCATTGGA", "TCGCGGTTGG", "CGTAGTTACC", "TCCAATCATC", "AATCGATAAT", "CCATTATCTA", "TCAACGTAAG", "TCTAATAGTA", "GATCGCTTCT", "CTAACTAGAT", "GCTGGAACTT", "AGGTTAGTTC", "CATTCGACGG", "CATTCAATCA", "CGGATTAGAA", "ATCGGCTATC", "ACGAAGTCAA", "TTACCTCGAC", "GGAGGATAGC", "GGCTCTCTAT", "CGGTCAAGAA", "CGCTCCTAAC", "ATCCATGACT", "AACCTGGTCT", "GGTACCGGCA", "AAGCCAGTTA", "TCTTGCCGAC", "AAGACCGTTG", "AGGTTAGCAT", "TTCGCCTCCA", "AGAGCCAAGG", "AATACCATCC", "AGCTCTCCTC", "AGCTTATCCG", "CATCTCTGCA", "ACCTGGCCAA", "TAACTGGTTA", "TTGCTAACGG", "ACTAGAGAGT", "AATGCCGCTT", "TATAGACGCA", "TCAATCGCAT", "TTCTTAATAA", "GTCCTAGAGG", "ATATTGATAC", "CCGCTGCCAG", "CAATTACCGT", "GGCCGTAGTC", "TAATGAACGA", "CCGTTCCTTA", "ATGGCTCTGC", "GTATAATACG", "GGCGAACTCG", "TTAATTGAAT", "TTAGGACCGG", "AAGTAAGAGC", "CCTTGGTCCA", "CATCAGAATG", "TTATAGCAGA", "TTACTTGGAA", "GCTCAGCCGG", "ACGTCCGCAG", "TTGCGAGGCA", "TTCCAACCGC", "TCAAGCCGAT", "CTTGCAACCT", "CCATCGCGAA", "TAGACTTCTT", "GTCCTTAAGA", "AGTAACGGTC", "GTTCGTCAGA", "CGCCTAATGC", "ACCGGAATTA", "TAGGCCATAG", "TAACTCTTAG", "TATGAGTTAA", "TATCATGATC", "GAGCATATGG", "TAACGATCCA", "CGGCGTAACT", "CGTCGCAGCC", "GTAGCTCCAT", "GTCCTACTTG", "GGTAGGTTAG", "GAGCATCATT", "CCGCTCCGGC", "TTCTTCCGGT", "AGGAGAGAAC", "TAACTCAATT", "ACTATAGGTT", "AGGTATACTC", "TTCATAGGAC", "GGAGGCCTCC", "TTCAATATAA", "ACGTCATATA", "CGGTTGCGCG", "CAAGGAGGTC", "TTACGATGAA", "TTGCTGGCAT", "ATTCGACCAA", "CCGCGGCTCA", "GTTACGCAAG", "AGCCGGTACC", "ACCTCTATCT", "GGACTACTAC", "GTATCATCGA", "CCGCGATTAT", "ATTCAGGTAC", "ATGGAATTGG", "GACGAAGCGT", "CTTGCAGTAG", "CTTGGTAATG", "CAAGTCGACC", "TAACGAATTG", "TTATTCTGAG", "TTATTATGGT", "ATATGAGCCA", "CAACCAGTAC", "CATCCGACTA", "CCGCAAGTTC", "CAGGAGGAGA", "GATATCGGCG", "CCAGTCCTCT", "CATAGTTCGG", "CGTAATGCAG", "CCGTTCGGAT", "CCATAAGTCC", "GGCAATGAGA", "CGGTTATGCC", "TGGCCGGCCT", "AGCTGCAATA", "TGGCCATGCA", "TGACGCTCCG" ]

    # 读取输入文件为 DataFrame，使用制表符作为分隔符
    df = pd.read_csv(input_file, sep='\t')

    # 提取 CB 列后缀作为一个新列用于排序（比如 2450_1_AACCATTGGA => AACCATTGGA）
    df["CB_suffix"] = df["CB2_ID"].apply(lambda x: x.split("_")[-1])

    # 创建一个字典，CB_suffix 到排序索引的映射
    sort_index = {cb: i for i, cb in enumerate(sort_order)}

    # 为每一行匹配排序序号，若没有找到则赋值为很大的数字（排到最后）
    df["sort_key"] = df["CB_suffix"].apply(lambda x: sort_index.get(x, float("inf")))

    # 按照排序键排序
    df_sorted = df.sort_values(by="sort_key").drop(columns=["CB_suffix", "sort_key"])

    # 输出为 .xls（其实是 .tsv 表格）文件
    df_sorted.to_csv(output_file, sep='\t', index=False)

    print(f"排序完成，输出保存为：{output_file}")

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("用法: python CB2_sort.py 输入文件 输出文件")
        print("例如: python CB2_sort.py CB2ID_2450_1_Summary_withCellNum.txt CB2ID_2450_1_Summary_withCellNum_sort.xls")
        sys.exit(1)
    
    input_file = sys.argv[1]
    output_file = sys.argv[2]
    
    main(input_file, output_file)
